server:
  port: 8002

spring:
  application:
    name: cloud-service-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_db?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-one.com:7001/eureka
  #      defaultZone: http://eureka-one.com:7001/eureka, http://eureka-two.com:7002/eureka
  instance:
    instance-id: provider-two
    prefer-ip-address: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: io.gitee.oldpassive.spring.cloud.entities