server:
  port: 80

spring:
  application:
    name: cloud-service-consumer

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-one.com:7001/eureka, http://eureka-two.com:7002/eureka